server:
  port: 8082
spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:postgresql://localhost:5432/stagingdev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
 